=== FerminBlancoRamirez/Marcas/XML/Libreria.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <!-- Definimos elementos finales-->
    <xs:element name="titulo" type="xs:string"/>
    <xs:element name="autor" type="xs:string"/>
    <xs:element name="anio" type="xs:integer"/>
    <xs:element name="genero" type="xs:string"/>
    <!--Declaracion del elemento libro-->
    <xs:element name="libro">
        <xs:complexType>
            <xs:sequence>
            <xs:element ref="titulo"/>
            <xs:element ref="autor"/>
            <xs:element ref="anio"/>
            <xs:element ref="genero"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <!--Declaracion de elemento raiz-->
    <xs:element name="Libreria">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="libro" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <!-- Definimos los elementos libreria con estos cuatro simples-->
    <xs:element name="libreria">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="titulo" type="xs:string"/>
                <xs:element name="autor" type="xs:string"/>
                <xs:element name="anio" type="xs:integer"/>
                <xs:element name="genero" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <!-- declaracion de genero como enumerado-->
    <xs:element name="genero">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="Ficcion"/>
                <xs:enumeration value="Distopia"/>
                <xs:enumeration value="Realismo mágico"/>
                <xs:enumeration value="Distopía"/>
                <xs:enumeration value="Terror"/>
                <xs:enumeration value="Romance"/>
                <xs:enumeration value="Ciencia ficción"/>
                <xs:enumeration value="Misterio histórico"/>
                <xs:enumeration value="Drama"/>
                <xs:enumeration value="Novela psicológica"/>
                <xs:enumeration value="Suspense"/>
                <xs:enumeration value="Juvenil"/>
                <xs:enumeration value="Thriller"/>
                <xs:enumeration value="Fantasía filosófica"/>
                <xs:enumeration value="Ficción existencial"/>
                <xs:enumeration value="Surrealismo"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

</xs:schema>

=== FerminBlancoRamirez/Marcas/XML/Libreria.xml
<?xml version="1.0" encoding="UTF-8" ?>
<Libreria xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="Libreria.xsd">
    <libro>
        <titulo>El gran Gatsby</titulo>
        <autor>F.Scott Fitzgerald</autor>
        <anio>1925</anio>
        <genero>Ficcion</genero>
    </libro>
    <libro>
        <titulo>1849</titulo>
        <autor>George Orwell</autor>
        <anio>1949</anio>
        <genero>Distopia</genero>
    </libro>
    <libro>
        <titulo>Cien años de soledad</titulo>
        <autor>Gabriel García Márquez</autor>
        <anio>1967</anio>
        <genero>Realismo mágico</genero>
    </libro>
    <libro>
        <titulo>1984</titulo>
        <autor>George Orwell</autor>
        <anio>1949</anio>
        <genero>Distopía</genero>
    </libro>
    <libro>
        <titulo>El resplandor</titulo>
        <autor>Stephen King</autor>
        <anio>1977</anio>
        <genero>Terror</genero>
    </libro>
    <libro>
        <titulo>Orgullo y prejuicio</titulo>
        <autor>Jane Austen</autor>
        <anio>1813</anio>
        <genero>Romance</genero>
    </libro>
    <libro>
        <titulo>Crónicas marcianas</titulo>
        <autor>Ray Bradbury</autor>
        <anio>1950</anio>
        <genero>Ciencia ficción</genero>
    </libro>
    <libro>
        <titulo>El nombre de la rosa</titulo>
        <autor>Umberto Eco</autor>
        <anio>1980</anio>
        <genero>Misterio histórico</genero>
    </libro>
    <libro>
        <titulo>El gran Gatsby</titulo>
        <autor>F. Scott Fitzgerald</autor>
        <anio>1925</anio>
        <genero>Drama</genero>
    </libro>
    <libro>
        <titulo>Fundación</titulo>
        <autor>Isaac Asimov</autor>
        <anio>1951</anio>
        <genero>Ciencia ficción</genero>
    </libro>
    <libro>
        <titulo>Crimen y castigo</titulo>
        <autor>Fiódor Dostoyevski</autor>
        <anio>1866</anio>
        <genero>Novela psicológica</genero>
    </libro>
    <libro>
        <titulo>La sombra del viento</titulo>
        <autor>Carlos Ruiz Zafón</autor>
        <anio>2001</anio>
        <genero>Suspense</genero>
    </libro>
    <libro>
        <titulo>Bajo la misma estrella</titulo>
        <autor>John Green</autor>
        <anio>2012</anio>
        <genero>Juvenil</genero>
    </libro>
    <libro>
        <titulo>El código Da Vinci</titulo>
        <autor>Dan Brown</autor>
        <anio>2003</anio>
        <genero>Thriller</genero>
    </libro>
    <libro>
        <titulo>La metamorfosis</titulo>
        <autor>Franz Kafka</autor>
        <anio>1915</anio>
        <genero>Fantasía filosófica</genero>
    </libro>
    <libro>
        <titulo>Ensayo sobre la ceguera</titulo>
        <autor>José Saramago</autor>
        <anio>1995</anio>
        <genero>Ficción existencial</genero>
    </libro>
    <libro>
        <titulo>Rayuela</titulo>
        <autor>Julio Cortázar</autor>
        <anio>1963</anio>
        <genero>Surrealismo</genero>
    </libro>
</Libreria>
